image: node:latest

stages:
  - mirror
  - makedoc
  - publish

makedoc:
  stage: makedoc
  script:
    - DOC_URL=https://doc.y.gy
    #install
    - yarn add docdash-orange jsdoc jsdoc-to-markdown --dev
    # generate index.js from raw
    - cat index.raw.js > index.js
    - sed -i "s|DOC_URL|$DOC_URL/$CI_PROJECT_NAME|g" index.js
    # generate doc
    - cat README_basic.md > README.md
    - node_modules/.bin/jsdoc2md index.js >> README.md
    - node_modules/.bin/jsdoc index.js -t node_modules/docdash-orange --readme README_basic.md
    # copy logo.jpg
    - cp logo.jpg out/logo.jpg || true
    # upload html doc
    - cd out && tar -cf ../archive.tar . && cd ..
    - curl -F file=@archive.tar "$DOC_URL/?project-name=$CI_PROJECT_NAME&token=$DOC_HOST_TOKEN" ; echo
    # commit generated readme back to repo
    - git config --global user.email "runner@$CI_SERVER_HOST"
    - git config --global user.name "runner"
    - git remote remove origin
    - git remote add origin https://runner:${RUNNER_PASSWORD}@$CI_SERVER_HOST/$CI_PROJECT_PATH.git
    - git add README.md index.js 
    - git commit README.md index.js -m "🤖 makedoc [skip ci]" || true
    - git push --set-upstream origin HEAD:master || true

mirror:
  stage: mirror
  script:
    - DOC_URL=https://doc.y.gy
    #install
    - yarn add docdash-orange jsdoc jsdoc-to-markdown --dev
    # generate index.js from raw
    - cat index.raw.js > index.js
    - sed -i "s|DOC_URL|$DOC_URL/$CI_PROJECT_NAME|g" index.js
    # generate doc
    - cat README_basic.md > README.md
    - node_modules/.bin/jsdoc2md index.js >> README.md
    - git config --global user.email "runner@$CI_SERVER_HOST"
    - git config --global user.name "runner"
    - git add -A
    - git commit -m "🤖 mirror"
    - curl -u "firstdorsal:$GITHUB_TOKEN" https://api.github.com/user/repos -d '{"name":"$CI_PROJECT_NAME"}'
    - git remote remove origin
    - git remote add origin https://firstdorsal:${GITHUB_TOKEN}@github.com/$CI_PROJECT_PATH.git
    - git push -u origin master



publish:
  stage: publish
  script:
    - DOC_URL=https://doc.y.gy
    #generate index.js
    - cat index.raw.js > index.js
    - sed -i "s|DOC_URL|$DOC_URL/$CI_PROJECT_NAME|g" index.js
    #generate readme doc
    - yarn add jsdoc jsdoc-to-markdown --dev
    - cat README_basic.md > README.md
    - node_modules/.bin/jsdoc2md index.js >> README.md
    #publish to npm
    - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}'>.npmrc
    - npm publish
